version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "9312:9311"
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - "27019:27017"
